apiVersion: apps/v1
kind: Deployment
metadata:
  name: barmaq-dapp
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barmaq-dapp
  template:
    metadata:
      labels:
        app: barmaq-dapp
    spec:
      containers:
      - name: barmaq-dapp
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
