apiVersion: v1
kind: Service
metadata:
  name: barmaq-app-service
  namespace: app
spec:
  selector:
    app: barmaq-dapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort