name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: barmaq/barmaq-dapp
  K8S_NAMESPACE: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Забираем код
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Собираем и пушим образ
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      # 4. Устанавливаем kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      # 5. Деплоим в Kubernetes
      - name: Deploy to Cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

          # Применяем манифесты
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          # Если есть Ingress:
          #kubectl apply -f k8s/ingress.yaml

          # Проверяем поды
          kubectl get pods -n ${{ env.K8S_NAMESPACE }}